### PR TITLE
Fix Saucelab IE9 timeouts 

### PR DESCRIPTION
**Pull request by davelosert**
As stated in #55 I am going to use this PR to check if lowering the concurrency in karma will help us with the IE9 timeouts we are experiencing.

### CODE REVIEW

**Comment by davelosert** [comment]
Just documenting here: I saw that we already had a concurrency limit set to `3`. I even lowered it to `2` (which rises the build time tremendously) - without success. Maybe the error is with IE9? I'm going to further investiage.

**Comment by davelosert** [comment]
Well this is just funny:
IE9 seems to be working now - even though i reverted all changes back to normal.

There are two other Problems now:
With node 0.10.46, eslint doesn't seem to be installed correctly by travis - so the built fails because of

    sh: 1: eslint: not found

Then both with `4.3` and `stable` the coverage report fails with:

    > lcov-result-merger 'coverage/**/lcov.info' | coveralls; exit 0
    /home/travis/build/chaijs/type-detect/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
    Bad response: 504 <!DOCTYPE html>

Followed by an printed out HTML Page with meters of font-imports...

All this somehow makes me feel that TravisCI is currently not very reliable in its built. It also feels very slow to me on the Web-GUI. Im gonna let it rest for now and try it again another day. But as the tests are passing, I guess we can start merging and closing most of the PRs that had IE9-Errors previously.

**Comment by meeber** [comment]
What an incredibly frustrating problem. I haven't run into this kind of issue with any other project so I wonder if there's something else unique about type-detects travis config or other tooling that's triggering this behavior. Hmm...

**Comment by davelosert** [comment]
@meeber Haha yeah, frustrating. But who doesn't like a challenge? ;)

And thanks for the hint - I think my next step is going to be comparing the Travis-Config with other Projects (let's say chai) and see if I can find some uniquness somehow connected to the problem.

**Comment by keithamus** [comment]
IE9 seems to be a lot better now. I wonder if this was a case of SauceLabs not having enough IE9 vms for a period? I'll close this and we can re-open another day if we keep experiencing it.

**Pull request closed without merging**
