### PR TITLE
docs: lowercase "Symbol" in README.md

### LINKED ISSUE #102: Symbol issue (lowercase)
The following assertion fails:

`assert(type(Symbol()) === 'Symbol');`  // AssertionError

It is taken from the README.md file. The actual result of the type-check is 'symbol' (lowercase)

So, `type(Symbol()) !== Symbol.name`.

### PR DESCRIPTION
**Pull request by shvaikalesh**
Fixes #102

### CODE REVIEW

**Comment by keithamus** [comment]
One more from @chaijs/type-detect?

**Comment by meeber** [comment]
How (if at all) does this relate to [this test](https://github.com/chaijs/type-detect/blob/c7895e499ecc0a93c567adef9fa2b33eec13d2ab/test/index.js#L140-L143)?

**Comment by keithamus** [comment]
Looks like that test is kind of invalid due to the typeof optimisation. We could just delete the test?

**Comment by shvaikalesh** [comment]
The test ensures that `type({ [Symbol.toStringTag]: "Symbol" })` produces `"Symbol"` and does not conflict with code paths for symbol primitives. So no, it is not related with the issue in question.

**Comment by keithamus** [comment]
Good point, thanks @shvaikalesh

**Pull request merged**
