### PR TITLE
fix: detection logic in quasi-browser environments

### PR DESCRIPTION
**Pull request by meeber**
- Always use `window` object for detecting DOM-related types; a
  quasi-browser environment can be loaded on top of a server
  environment.
- Always verify that each property of `window` exists before using
  it for type detection; nothing is guaranteed in a quasi-browser
  environment.
- Refactor to remove redundant `instanceof window.HTMLElement`.

Fixes https://github.com/chaijs/chai/issues/1094

### CODE REVIEW

**Comment by meeber** [comment]
Obviously not ready to merge yet, as a test is failing. Ran out of time to troubleshoot right now. Will circle back another day.

**Comment by meeber** [comment]
Pinging @chaijs/chai

**Comment by astorije** [comment]
Ah, just realized I don't have permission to merge :man_shrugging:

**Comment by keithamus** [comment]
@astorije I've added you to the type-detect team.

**Pull request merged**
