### PR TITLE
Validate javascript snippets in the README

### PR DESCRIPTION
**Pull request by fvictorio**
Hi. A friend and I are working on a tool for validating javascript snippets in the markdown files of a project (the README being the obvious use case). It's called [chimi](https://github.com/Huemul/chimi).

It's pretty much a work in progress, but we are looking for projects that can benefit from it and that are willing to give it a try.

This PR adds chimi as a dev dependency and also fixes the issues in the readme that it helped to find. I also temporarily modified the `rollup.js` file to make it work (it seems like you are working on that as I write this).

Let us know if you are interested! And if you aren't, I can make a separate PR with just the README changes.

Thanks!

### CODE REVIEW

**Comment by keithamus** [comment]
Thanks for putting the effort into this @fvictorio! I think it's a great idea to lint the README to keep things valid javascript; however I have some reservations about adding a whole new tool in to do this. It looks [like there is an eslint plugin](https://github.com/eslint/eslint-plugin-markdown) that can lint markdown, which we could use to keep to the same coding standards we have in the codebase, and this will also keep the number of configuration files down to a minimum.

Let's see how other maintainers, @meeber and @vieiralucas feel about this before we progress anywhere though.

**Comment by fvictorio** [comment]
Hi, thanks for the answer! I totally understand not wanting to add another tool if it doesn't add enough value.

Just to clarify, though: this _runs_ the snippets and checks that there are no runtime errors. For example, the problem with `Symbol` in the readme wouldn't have been caught by the linter.

**Comment by keithamus** [comment]
Hmm, interesting. What was the problem with Symbol? I didn't see that?

I just quickly tried the eslint markdown plugin and it seems to have caught all the errors in this PR (plus a few more based on our lint config).  I understand that wont always be the case; it certainly is quite compelling to have the README validated almost like actual tests, though.

**Comment by fvictorio** [comment]
Oh, you are right, I was confused with a previous version that had the type of Symbol as `Symbol` (capitalized). That was fixed since the previous time I tried our tool in this repo, but it's the kind of error that would have caught.

Anyway, thanks for the feedback! Even if you decide that `chimi` is not for this project, you've given us a lot to think about.

**Comment by vieiralucas** [comment]
Hey @fvictorio, thanks for working on this.
`chimi` looks very interesting and I really like the idea, but I'm with @keithamus here on adding a whole new tool for this. It looks like the eslint plugin is a good enough solution for us.

I actually really enjoyed that eslint plugin, can we add that? 😸

**Comment by keithamus** [comment]
I'm going to close this for staleness, if we want to re-investigate we can in a new PR.

Thanks all!

**Pull request closed without merging**
