### PR TITLE
fix(karma): ensure job number reflects CI environment

### LINKED ISSUE #111: Build failing due to sauce tunnel issue
Sauce is reporting the error as being "Your test errored. No active tunnel found for identifier 1509755873974". That number looks to be milliseconds since epoch from [here](https://github.com/chaijs/type-detect/blob/49b70623d24aa93e2a35f108ff1af0fc71750e7a/karma.conf.js#L5), but I think what we need is the Travis job number from [here](https://github.com/chaijs/type-detect/blob/49b70623d24aa93e2a35f108ff1af0fc71750e7a/karma.conf.js#L25)?

### PR DESCRIPTION
**Pull request by keithamus**
Fixes #111

### CODE REVIEW

**Comment by keithamus** [comment]
Sorry, being lazy and using the web editor. We should squash this down to one commit when merged.

**Comment by meeber** [comment]
@keithamus With my extremely limited Sauce/Travis/Karma knowledge, I'm not seeing anything obvious regarding the new push and pr failures.

**Comment by keithamus** [comment]
Looks as though sauce connect is hanging. This is a new one on me 😆

**Comment by keithamus** [comment]
Oookay it looks like Travis+SauceLabs _actually has support for running in PRs_ (https://docs.travis-ci.com/user/jwt) and so I'm going to take a stab at doing that later this evening, which will hopefully fix this failure as a side effect, and we'll have saucelabs running in PRs which would be awesome.

**Comment by keithamus** [comment]
@meeber @vieiralucas I believe this is now green accross the board 😄 🎉. Check out the Travis build logs to see SauceLabs is running in both the push CI and PR CI - meaning that we can now test PRs in IE10, Safari 10, and Edge 13 with Saucelabs, Chrome latest, Firefox latest with built in Travis, and IE11 with Appveyor 🎉

**Comment by meeber** [comment]
@keithamus Awesome, this looks much cleaner than before. One thing though: although the travis build are passing, the build logs for the sauce tests make it look like nothing is being tested in IE10, only Safari and Edge. This may just be a logging issue; when I follow the link to the sauce website for the IE 10 tests, the metadata shows:

> "totalTime":281,
> "skipped":35,
> "disconnected":false,
> "success":111,
> "failed":0,
> "netTime":17,
> "error":false,
> "total":146

**Comment by keithamus** [comment]
Yeah this looks like a logging issue. Let's merge this one, and I can figure out IE10 logging later.

**Pull request merged**
