### PR TITLE
Build improvements

### LINKED ISSUE #109: Problem releasing new version
Merging #91 didn't trigger a release. Found this in the [travis logs](https://travis-ci.org/chaijs/type-detect/jobs/295118314):

> 6.95s$ travis-after-all && npm run semantic-release
> [travis-after-all] Job succeeded (40027526e0227d81659090077756bde5fb9776ff1d5e08fb38f991cd2a5144cc)
> [travis-after-all] Waiting for 427.2, 427.3, 427.4 and 427.5 to be done...
> [travis-after-all] Failed to parse JSON from "https://api.travis-ci.org/jobs/295118317".
> Error: Cannot read property 'indexOf' of null

### PR DESCRIPTION
**Pull request by keithamus**
This makes several improvements to the build, including switching things over to rollup, introducing appveyor as a CI (which can run IE11 tests for us, without needing saucelabs), using Chrome+Firefox locally in CI (rather than using saucelabs), and introducing a package-lock for faster installs.

Fixes #109 #110

### CODE REVIEW

**Comment by keithamus** [comment]
This makes the travis logs look like this:

image

Which I think is pretty darn swell.

**Comment by keithamus** [comment]
I have to pause on this for now. Outstanding:

 - [ ] figure out why Appveyor is breaking and fix it
 - [ ] figure out why nyc isn't reporting anything and fix it
 - [ ] get green builds

If anyone wants to tackle the above while I'm away, feel free.

**Comment by meeber** [comment]
@keithamus With these new build tools and processes, what's the procedure for a contributor wanting to test their changes locally before submitting a PR? (I checked this branch out locally and ran `npm install` and then `npm test` and it failed due to lack of `ChromeHeadless` on my box.)

**Comment by keithamus** [comment]
@meeber Sorry; I had made the assumption that everyone testing would have Chrome 60+ on their box. I can make the change so this detects whatever browsers the user has available, and runs those instead.

**Comment by meeber** [comment]
@keithamus I just merged that other longstanding PR, so there's conflicts here now. Also need the auto-detection for Chrome during tests.

**Comment by keithamus** [comment]
Probablt worth ignoring `codecov` for now. But otherwise this is good to go 😄

**Comment by meeber** [comment]
Changes work for me. The build is failing cause of a minor linting error.

**Comment by keithamus** [comment]
@chaijs/type-detect if we can get an approval on this from one of you, and a merge from another, then I'll head on over to chai-http and chai-spies to get them both up to date with this.

**Pull request merged**
