### PR TITLE
fix: ensure stringIteratorExists checks String.prototype

### PR DESCRIPTION
**Pull request by keithamus**
This PR has no diff because it's just a commit message to trigger the build system to release @JakeChampion's fix as a 4.0.1 release.

### CODE REVIEW

**Comment by fracmak** [comment]
Any updates on when this is going to be released? I've actually hit this in my own project and would love to have this fix

**Comment by keithamus** [comment]
Looks like codacy was holding up the merge here. I've disabled it as a requirement as it doesn't seem reliable.

**Comment by keithamus** [comment]
@fracmak released as `4.0.1`

**Comment by fracmak** [comment]
Thank you!

**Pull request merged**
